from typing import Dict

from worlds.legend_of_dragoon.loc.location_data import LegendOfDragoonLocationData

enemy_table: Dict[str, LegendOfDragoonLocationData] = {
    "Commander":                    LegendOfDragoonLocationData("Seles",                        108_70001, "Enemy"),
    "Fruegel 1":                    LegendOfDragoonLocationData("Hellena 01",                   108_70002, "Enemy"),
    "Urobolus":                     LegendOfDragoonLocationData("Limestone Cave",               108_70003, "Enemy"),
    "Sandora Elite":                LegendOfDragoonLocationData("Hoax",                         108_70004, "Enemy"),
    "Kongol 1":                     LegendOfDragoonLocationData("Hoax",                         108_70005, "Enemy"),
    "Volcano Virage":               LegendOfDragoonLocationData("Hoax",                         108_70006, "Enemy"),
    "Fire Bird":                    LegendOfDragoonLocationData("Volcano Villude",              108_70007, "Enemy"),
    "Greham and Feyrbrand":         LegendOfDragoonLocationData("Dragon's Nest",                108_70008, "Enemy"),
    "Drake the Bandit":             LegendOfDragoonLocationData("Shrine of Shirley",            108_70009, "Enemy"),
    "Shirley":                      LegendOfDragoonLocationData("Shrine of Shirley",            108_70010, "Enemy"),
    "Gorgaga":                      LegendOfDragoonLocationData("Lohan",                        108_70011, "Enemy"),
    "Serfius":                      LegendOfDragoonLocationData("Lohan",                        108_70012, "Enemy"),
    "Danton":                       LegendOfDragoonLocationData("Lohan",                        108_70013, "Enemy"),
    "Atlow":                        LegendOfDragoonLocationData("Lohan",                        108_70014, "Enemy"),
    "Lloyd 1":                      LegendOfDragoonLocationData("Lohan",                        108_70015, "Enemy"),
    "Fruegel 2":                    LegendOfDragoonLocationData("Hellena 02",                   108_70016, "Enemy"),
    "Kongol 2":                     LegendOfDragoonLocationData("Black Castle",                 108_70017, "Enemy"),
    "Dragoon Doel":                 LegendOfDragoonLocationData("Black Castle",                 108_70018, "Enemy"),
    "Mappi":                        LegendOfDragoonLocationData("Barrens",                      108_70019, "Enemy"),
    "Valley Virage":                LegendOfDragoonLocationData("Valley of Corrupted Gravity",  108_70020, "Enemy"),
    "Gehrich and Mappi":            LegendOfDragoonLocationData("Home of Giganto",              108_70021, "Enemy"),
    "Lenus 1":                      LegendOfDragoonLocationData("Fletz Castle",                 108_70022, "Enemy"),
    "Ghost Commander":              LegendOfDragoonLocationData("Phantom Ship",                 108_70023, "Enemy"),
    "Lenus 2":                      LegendOfDragoonLocationData("Underwater Cavern",            108_70024, "Enemy"),
    "Forbidden Virage":             LegendOfDragoonLocationData("Evergreen Forest",             108_70025, "Enemy"),
    "Grand Jewel":                  LegendOfDragoonLocationData("Forbidden Land",               108_70026, "Enemy"),
    "Divine Dragon":                LegendOfDragoonLocationData("Mortal Dragon Mountain",       108_70027, "Enemy"),
    "Windigo":                      LegendOfDragoonLocationData("Kashua Glacier",               108_70028, "Enemy"),
    "Lloyd 2":                      LegendOfDragoonLocationData("Tower of Flanvel",             108_70029, "Enemy"),
    "Polter":                       LegendOfDragoonLocationData("Snowfield",                    108_70030, "Enemy"),
    "Last Kraken":                  LegendOfDragoonLocationData("Aglis",                        108_70031, "Enemy"),
    "Magician Faust":               LegendOfDragoonLocationData("Tower of Flanvel",             108_70032, "Enemy"),
    "Belzac":                       LegendOfDragoonLocationData("Vellweb",                      108_70033, "Enemy"),
    "Damia":                        LegendOfDragoonLocationData("Vellweb",                      108_70034, "Enemy"),
    "Kanzas":                       LegendOfDragoonLocationData("Vellweb",                      108_70035, "Enemy"),
    "Syuveil":                      LegendOfDragoonLocationData("Vellweb",                      108_70036, "Enemy"),
    "Kubila, Vector, and Selebus":  LegendOfDragoonLocationData("Zenebatos",                    108_70037, "Enemy"),
    "Ghost Feybrand":               LegendOfDragoonLocationData("Mayfil",                       108_70038, "Enemy"),
    "Ghost Regole":                 LegendOfDragoonLocationData("Mayfil",                       108_70039, "Enemy"),
    "Ghost Divine Dragon":          LegendOfDragoonLocationData("Mayfil",                       108_70040, "Enemy"),
    "Zackwell":                     LegendOfDragoonLocationData("Mayfil",                       108_70041, "Enemy"),
    "Imago":                        LegendOfDragoonLocationData("Divine Tree",                  108_70042, "Enemy"),
    "Michael":                      LegendOfDragoonLocationData("Moon That Never Sets",         108_70043, "Enemy"),
    "Moon Virage":                  LegendOfDragoonLocationData("Moon That Never Sets",         108_70044, "Enemy"),
    "Zieg Feld":                    LegendOfDragoonLocationData("Moon That Never Sets",         108_70045, "Enemy"),
    "Melbu Frahma":                 LegendOfDragoonLocationData("Moon That Never Sets",         108_70046, "Enemy"),
}
