from typing import Dict

from .item_data import LegendOfDragoonItemData, ItemCategory
from BaseClasses import ItemClassification as IC

consumables_table:  Dict[str, LegendOfDragoonItemData] = {
    "Angel's Prayer":       LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00001, IC.filler),
    "Healing Potion":       LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00002, IC.filler),
    "Healing Fog":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00003, IC.filler),
    "Healing Breeze":       LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00004, IC.filler),
    "Healing Rain":         LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00005, IC.filler),
    "Moon Serenade":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00006, IC.filler),
    "Sun Rhapsody":         LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00007, IC.filler),
    "Spirit Potion":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00008, IC.filler),
    "Body Purifier":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00009, IC.filler),
    "Depetrifier":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00010, IC.filler),
    "Mind Purifier":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00011, IC.filler),
    "Recovery Ball":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00012, IC.filler),
    "Black Rain":           LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00013, IC.filler),
    "Burn Out":             LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00014, IC.filler),
    "Burning Wave":         LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00015, IC.filler),
    "Dancing Ray":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00016, IC.filler),
    "Dark Mist":            LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00017, IC.filler),
    "Detonate Rock":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00018, IC.filler),
    "Down Burst":           LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00019, IC.filler),
    "Fatal Blizzard":       LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00020, IC.filler),
    "Flash Hall":           LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00021, IC.filler),
    "Frozen Jet":           LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00022, IC.filler),
    "Gravity Grabber":      LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00023, IC.filler),
    "Gushing Magma":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00024, IC.filler),
    "Meteor Fall":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00025, IC.filler),
    "Night Raid":           LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00026, IC.filler),
    "Pellet":               LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00027, IC.filler),
    "Psyche Bomb":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00028, IC.filler),
    "Psyche Bomb X":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00029, IC.filler),
    "Rave Twister":         LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00030, IC.filler),
    "Spark Net":            LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00031, IC.filler),
    "Spear Frost":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00032, IC.filler),
    "Spectral Flash":       LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00033, IC.filler),
    "Spinning Gale":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00034, IC.filler),
    "Thunderbolt":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00035, IC.filler),
    "Trans Light":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00036, IC.filler),
    "Attack Ball":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00037, IC.filler),
    "Charm Potion":         LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00038, IC.filler),
    "Magic Sig Stone":      LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00039, IC.filler),
    "Midnight Terror":      LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00040, IC.filler),
    "Pandemonium":          LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00041, IC.filler),
    "Panic Bell":           LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00042, IC.filler),
    "Poison Needle":        LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00043, IC.filler),
    "Sachet":               LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00044, IC.filler),
    "Smoke Ball":           LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00045, IC.filler),
    "Stunning Hammer":      LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00046, IC.filler),
    "Total Vanishing":      LegendOfDragoonItemData(ItemCategory.CONSUMABLE, 108_00047, IC.filler),
}
