from typing import Dict

from .item_data import LegendOfDragoonItemData, ItemCategory, ItemClassification as IC

equipment_table:  Dict[str, LegendOfDragoonItemData] = {
    "Active Ring":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10001, IC.useful),
    "Amulet":               LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10002, IC.useful),
    "Angel Robe":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10003, IC.useful),
    "Angel Scarf":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10004, IC.useful),
    "Armet":                LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10005, IC.useful),
    "Armor of Legend":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10006, IC.progression),
    "Armor of Yore":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10007, IC.progression),
    "Arrow of Force":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10008, IC.progression),
    "Attack Badge":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10009, IC.useful),
    "Axe":                  LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10010, IC.filler),
    "Bandana":              LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10011, IC.filler),
    "Bandits Ring":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10012, IC.useful),
    "Bandits Shoes":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10013, IC.progression),
    "Basher":               LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10014, IC.progression),
    "Bastard Sword":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10015, IC.filler),
    "Battle Axe":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10016, IC.useful),
    "Beast Fang":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10017, IC.useful),
    "Bemusing Arrow":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10018, IC.useful),
    "Blue Dragoon Armor":   LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10019, IC.progression),
    "Blue Sea Stone":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10020, IC.useful),
    "Bracelet":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10021, IC.useful),
    "Brass Knuckle":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10022, IC.useful),
    "Bravery Amulet":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10023, IC.useful),
    "Breast Plate":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10024, IC.useful),
    "Broad Sword":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10025, IC.filler),
    "Cape":                 LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10026, IC.filler),
    "Chain Mail":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10027, IC.useful),
    "Claymore":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10028, IC.progression),
    "Clothes":              LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10029, IC.filler),
    "Combat Shoes":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10030, IC.useful),
    "Dancer's Ring":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10031, IC.useful),
    "Dancer's Shoes":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10032, IC.progression),
    "Dancing Dagger":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10033, IC.useful),
    "Dark Dragoon Armor":   LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10034, IC.progression),
    "Darkness Stone":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10035, IC.useful),
    "Demon Stiletto":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10036, IC.useful),
    "Destone Amulet":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10037, IC.useful),
    "Destroyer Mace":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10038, IC.progression),
    "Detonate Arrow":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10039, IC.progression),
    "Diamond Claw":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10040, IC.useful),
    "Disciple Vest":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10041, IC.filler),
    "Dragon Buster":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10042, IC.progression),
    "Dragon Helm":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10043, IC.useful),
    "Dragon Shield":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10044, IC.useful),
    "Elude Cloak":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10045, IC.useful),
    "Emerald Earring":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10046, IC.useful),
    "Energy Girdle":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10047, IC.useful),
    "Fairy Sword":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10048, IC.progression),
    "Fake Power Wrist":     LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10049, IC.useful),
    "Fake Shield":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10050, IC.useful),
    "Falchion":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10051, IC.useful),
    "Felt Hat":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10052, IC.filler),
    "Flamberge":            LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10053, IC.useful),
    "Giganto Armor":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10054, IC.useful),
    "Giganto Helm":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10055, IC.useful),
    "Giganto Ring":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10056, IC.useful),
    "Gladius":              LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10057, IC.progression),
    "Glaive":               LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10058, IC.useful),
    "Gold Dragoon Armor":   LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10059, IC.progression),
    "Golden Stone":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10060, IC.useful),
    "Great Axe":            LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10061, IC.progression),
    "Guard Badge":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10062, IC.useful),
    "Halberd":              LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10063, IC.progression),
    "Heat Blade":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10064, IC.useful),
    "Heavy Mace":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10065, IC.useful),
    "Holy Ankh":            LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10066, IC.useful),
    "Indora's Axe":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10067, IC.progression),
    "Iron Kneepiece":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10068, IC.useful),
    "Iron Knuckle":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10069, IC.filler),
    "Jade Dragoon Armor":   LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10070, IC.progression),
    "Jade Stone":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10071, IC.useful),
    "Jeweled Crown":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10072, IC.useful),
    "Knight Helm":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10073, IC.useful),
    "Knight Shield":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10074, IC.useful),
    "Lance":                LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10075, IC.filler),
    "Leather Armor":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10076, IC.filler),
    "Leather Boots":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10077, IC.filler),
    "Leather Jacket":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10078, IC.filler),
    "Leather Shoes":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10079, IC.useful),
    "Legend Casque":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10080, IC.progression),
    "Lion Fur":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10081, IC.filler),
    "Long Bow":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10082, IC.useful),
    "Mace":                 LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10083, IC.filler),
    "Mage Ring":            LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10084, IC.useful),
    "Magic Ego Bell":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10085, IC.useful),
    "Magical Greaves":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10086, IC.useful),
    "Magical Hat":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10087, IC.useful),
    "Magical Ring":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10088, IC.useful),
    "Master's Vest":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10089, IC.useful),
    "Mind Crush":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10090, IC.useful),
    "Morning Star":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10091, IC.useful),
    "Panic Guard":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10092, IC.useful),
    "Partisan":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10093, IC.progression),
    "Phantom Shield":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10094, IC.useful),
    "Phoenix Plume":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10095, IC.useful),
    "Physical Ring":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10096, IC.useful),
    "Plate Mail":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10097, IC.useful),
    "Platinum Collar":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10098, IC.useful),
    "Poison Guard":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10099, IC.useful),
    "Power Wrist":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10100, IC.useful),
    "Pretty Hammer":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10101, IC.progression),
    "Protector":            LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10102, IC.useful),
    "Rainbow Dress":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10103, IC.useful),
    "Rainbow Earring":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10104, IC.useful),
    "Rapier":               LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10105, IC.filler),
    "Red Dragoon Armor":    LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10106, IC.progression),
    "Red Eye Stone":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10107, IC.useful),
    "Robe":                 LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10108, IC.useful),
    "Roses Hair Band":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10109, IC.useful),
    "Ruby Ring":            LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10110, IC.useful),
    "Sages Cloak":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10111, IC.useful),
    "Saint Armor":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10112, IC.useful),
    "Sallet":               LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10113, IC.filler),
    "Sapphire Pin":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10114, IC.useful),
    "Satori Vest":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10115, IC.useful),
    "Scale Armor":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10116, IC.filler),
    "Shadow Cutter":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10117, IC.useful),
    "Short Bow":            LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10118, IC.filler),
    "Silver Dragoon Armor": LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10119, IC.progression),
    "Silver Stone":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10120, IC.useful),
    "Silver Vest":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10121, IC.filler),
    "Soft Boots":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10122, IC.useful),
    "Soul Eater":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10123, IC.progression),
    "Soul Headband":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10124, IC.useful),
    "Sparkle Arrow":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10125, IC.useful),
    "Sparkle Dress":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10126, IC.useful),
    "Spear":                LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10127, IC.filler),
    "Spear of Terror":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10128, IC.useful),
    "Spirit Cloak":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10129, IC.useful),
    "Spirit Ring":          LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10130, IC.useful),
    "Spiritual Ring":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10131, IC.useful),
    "Stardust Boots":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10132, IC.useful),
    "Stun Guard":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10133, IC.useful),
    "Talisman":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10134, IC.useful),
    "Therapy Ring":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10135, IC.progression),
    "Thunder Fist":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10136, IC.progression),
    "Tiara":                LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10137, IC.useful),
    "Tomahawk":             LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10138, IC.useful),
    "Twister Glaive":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10139, IC.useful),
    "Ultimate Wargod":      LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10140, IC.useful),
    "Violet Dragoon Armor": LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10141, IC.progression),
    "Violet Stone":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10142, IC.useful),
    "Virulent Arrow":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10143, IC.useful),
    "War Hammer":           LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10144, IC.useful),
    "Wargod Calling":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10145, IC.useful),
    "Wargods Amulet":       LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10146, IC.useful),
    "Wargods Sash":         LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10147, IC.useful),
    "Warrior Dress":        LegendOfDragoonItemData(ItemCategory.EQUIPMENT, 108_10148, IC.useful),
}
