from typing import Dict

from .item_data import LegendOfDragoonItemData, ItemCategory, ItemClassification as IC

goods_table:  Dict[str, LegendOfDragoonItemData] = {
    "Red Dragoon Spirit":    LegendOfDragoonItemData(ItemCategory.GOOD, 108_20001, IC.progression),
    "Blue Dragoon Spirit":   LegendOfDragoonItemData(ItemCategory.GOOD, 108_20002, IC.progression),
    "Jade Dragoon Spirit":   LegendOfDragoonItemData(ItemCategory.GOOD, 108_20003, IC.progression),
    "Gold Dragoon Spirit":   LegendOfDragoonItemData(ItemCategory.GOOD, 108_20004, IC.progression),
    "Violet Dragoon Spirit": LegendOfDragoonItemData(ItemCategory.GOOD, 108_20005, IC.progression),
    "Silver Dragoon Spirit": LegendOfDragoonItemData(ItemCategory.GOOD, 108_20006, IC.progression),
    "Dark Dragoon Spirit":   LegendOfDragoonItemData(ItemCategory.GOOD, 108_20007, IC.progression),
    "Divine Dragoon Spirit": LegendOfDragoonItemData(ItemCategory.GOOD, 108_20008, IC.progression),
    "War Bulletin":          LegendOfDragoonItemData(ItemCategory.GOOD, 108_20009, IC.filler),
    "Fathers Stone":         LegendOfDragoonItemData(ItemCategory.GOOD, 108_20010, IC.progression),
    "Prison Key":            LegendOfDragoonItemData(ItemCategory.GOOD, 108_20011, IC.progression),
    "Axe from the Shack":    LegendOfDragoonItemData(ItemCategory.GOOD, 108_20012, IC.progression),
    "Good Spirits":          LegendOfDragoonItemData(ItemCategory.GOOD, 108_20013, IC.progression),
    # "Shiny Bag":             LegendOfDragoonItemData(ItemCategory.GOOD, 108_20014, IC.progression),
    "Water Bottle":          LegendOfDragoonItemData(ItemCategory.GOOD, 108_20015, IC.progression),
    "Life Water":            LegendOfDragoonItemData(ItemCategory.GOOD, 108_20016, IC.progression),
    "Magic Oil":             LegendOfDragoonItemData(ItemCategory.GOOD, 108_20017, IC.progression),
    "Yellow Stone":          LegendOfDragoonItemData(ItemCategory.GOOD, 108_20018, IC.progression),
    "Blue Stone":            LegendOfDragoonItemData(ItemCategory.GOOD, 108_20019, IC.progression),
    "Red Stone":             LegendOfDragoonItemData(ItemCategory.GOOD, 108_20020, IC.progression),
    "Letter from Lynn":      LegendOfDragoonItemData(ItemCategory.GOOD, 108_20021, IC.progression),
    "Pass for Valley":       LegendOfDragoonItemData(ItemCategory.GOOD, 108_20022, IC.progression),
    "Kates Bouquet":         LegendOfDragoonItemData(ItemCategory.GOOD, 108_20023, IC.progression),
    "Key to Ship":           LegendOfDragoonItemData(ItemCategory.GOOD, 108_20024, IC.progression),
    "Boat License":          LegendOfDragoonItemData(ItemCategory.GOOD, 108_20025, IC.progression),
    "Dragon Blocker":        LegendOfDragoonItemData(ItemCategory.GOOD, 108_20026, IC.progression),
    "Moon Gem":              LegendOfDragoonItemData(ItemCategory.GOOD, 108_20027, IC.progression),
    "Moon Dagger":           LegendOfDragoonItemData(ItemCategory.GOOD, 108_20028, IC.progression),
    "Moon Mirror":           LegendOfDragoonItemData(ItemCategory.GOOD, 108_20029, IC.progression),
    # "Omega Bomb":            LegendOfDragoonItemData(ItemCategory.GOOD, 108_20030, IC.progression),
    # "Omega Master":          LegendOfDragoonItemData(ItemCategory.GOOD, 108_20031, IC.progression),
    "Law Maker":             LegendOfDragoonItemData(ItemCategory.GOOD, 108_20032, IC.progression),
    "Law Output":            LegendOfDragoonItemData(ItemCategory.GOOD, 108_20033, IC.progression),
    # "Gold Dragoon Spirit 2": LegendOfDragoonItemData(ItemCategory.GOOD, 108_20034, IC.useful),
    # "Magic Shiny Bag":       LegendOfDragoonItemData(ItemCategory.GOOD, 108_20035, IC.progression),
    "Vanishing Stone":       LegendOfDragoonItemData(ItemCategory.GOOD, 108_20036, IC.progression),
    "Lavitzs Picture":       LegendOfDragoonItemData(ItemCategory.GOOD, 108_20037, IC.progression),
}